<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_EmptyBlock" Id="{ff56077f-bb7b-4ae0-9c6e-4b14dcab3937}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_EmptyBlock
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_EmptyBlock">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>