<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="PRG_Subscription" Id="{566e87ad-2ff3-47bb-b7ad-b791e069422f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Subscription
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PRG_Subscription">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>